### ISSUE TITLE
Permanent Redirect caused by recent privacyIDEA installations

### ISSUE THREAD

**Issue by martinhaase** [wraezor/privacyIDEA-shibboleth-tfa#3]
With current privacyIDEA installations, we see this in the IdP logs:
>> Host: **privacyIDEA host**
>> GET /token?user=test1
...
<< HTTP/1.1 308 PERMANENT REDIRECT
<< Location: **privacyIDEA host**/token/?user=test1

Note the slash "/" preceding the "?user=test" in the permanent Redirect.

This can be fixed by patching src/main/java/ca/ab/concordia/privacyIDEAtfa/piConnection.java: replace the occurences of "/token" with "/token/" (also note the trailing slash).

**Comment by wraezor** [comment]
Thanks.  Fixed.
